@startuml
actor Пользователь
participant Фронт
participant СервисСозданияЗаказов
participant СервисУведомлений
participant СервисОплаты
participant СервисПодсказкиАдресов
participant СервисПоискаВодителей

Пользователь -> Фронт : Создать заказ
Фронт -> СервисСозданияЗаказов : Запрос на создание заказа (REST)
СервисСозданияЗаказов -> СервисУведомлений : Уведомление о новом заказе (REST)
СервисСозданияЗаказов -> СервисОплаты : Запрос на оплату (REST)
СервисОплаты -> СервисСозданияЗаказов : Подтверждение оплаты (REST)

Фронт -> СервисПодсказкиАдресов : Запрос подсказок адресов (REST)
СервисПодсказкиАдресов -> Фронт : Подсказки адресов

Фронт -> СервисПоискаВодителей : Запрос на поиск водителей (WebSocket)
СервисПоискаВодителей -> Фронт : Данные о доступных водителях (WebSocket)
СервисПоискаВодителей -> СервисУведомлений : Уведомление о найденном водителе (REST)

Фронт -> СервисУведомлений : Запрос статуса поездки (REST)
СервисУведомлений -> Фронт : Статус поездки
@enduml
