@startuml
|Планирование|

:Планирование спринта (выбор задач из бэклога);
|Разработка|
:Разработка (кодирование);
fork
    :Тестирование;
fork again
    :Ревью кода;
end fork
:Деплой на тестовую среду;
|QA-команда|
:Тестирование QA-командой;
while (ошибки?) is (да)

  :Фиксация багов и их устранение.;

endwhile (нет)

:Деплой на продакшн;

@enduml
