@startuml
|Бобры|
start
:Найти дерево;

|Дерево|
if (Состояние дерева) then (Гнилое)
    :Ошибка: дерево гнилое;
    stop
else (Подходит)
    :Выбор дерева;

    if (Условия выбора выполнены?) then (да)
        :Выбор дерева завершён;

        |Платина|
        if (Условия для строительства выполнены?) then (да)
            :Строительство успешно завершено;
            stop
        else (нет)
            :Ошибка: условия для строительства не выполнены;
            stop
        endif
    else (нет)
        :Ошибка выбора дерева;
        stop
    endif
endif
@enduml
