@startuml
start

:Пользователь заходит на платформу;
:Просмотр главной страницы;

if (Нажать "Зарегистрироваться"?) then (да)
  :Ввод данных (имя, email, пароль);
  if (Данные введены корректно?) then (да)
    :Отправить письмо с подтверждением на email;
    if (Email подтвержден?) then (да)
      fork
        :Заполнение профиля;
          :Добавление дополнительной информации (фото, биография, интересы);
          :Выбор уровня подготовки (начинающий, средний, продвинутый);
      fork again
        :Выбор курсов;
          :Просмотр доступных курсов;
          :Фильтрация курсов по категориям или сложности;
          :Добавление выбранных курсов в список "Мои курсы";
      end fork
      if (Курс платный?) then (да)
        :Выбор способа оплаты;
        :Подтверждение оплаты;
      else (нет)
      endif
      :Доступ к материалам;
        :Переход к списку курсов;
        :Начало обучения;
      :Обратная связь;
        :Получение уведомлений о новых материалах;
        :Возможность оставить отзыв о курсах;
      stop
    else (нет)
      :Отправить повторное письмо;
      detach;
    endif
  else (нет)
    :Вернуться к вводу данных;
  endif
else (нет)
  :Войти как гость;
  stop
endif

@enduml
