@startuml
|Пользователь|
:пользователь заходит на платформу;
if (Нажать 'Зарегистрироваться'?) then (да)
    :Нажать Зарегистрироваться;
else (нет)
    :Войти как гость;
endif
|регистрация|
:Создание учетной записи;
:Ввод (имя, email, пароль);
if (Данные введены корректно?) then (да)
    :Отправить письмо с подтверждением;
else (нет)
    :Вернуться к вводу данных;
    kill
endif
|подтверждения|
:отправка письма; 
if (посьмо пришло) then (нет)
    :отказ;
else (да)
:Переход по ссылке из письма для активации аккаунта;
:Добавление дополнительной информации фото, биография, интересы;
:	Выбор уровня подготовки начинающий, средний, продвинутый;
|Выбор курсов|
:Просмотр доступных курсов;
:Фильтрация курсов по категориям или сложности;
:  	Добавление выбранных курсов в список "Мои курсы".;
|Оплата курсов|
:выбрать способ оплаты;
:Подтверждение оплаты;
if (оплата прошла) then (да)
   :Переход к списку курсов;  
   :Начало обучения;
else (нет)
|подтверждения|
    :отказ;
    kill
@enduml
